import type { Metadata } from "next";
import { DynamicBreadcrumb } from "@/components/bank-dashboard/dynamic-breadcrumb"
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ColorThemeProvider } from "@/components/color-theme-provider"
import { CardSettingsProvider } from "@/components/card-settings-provider"
import { PersonaProvider } from "@/components/persona-provider"
import { AppSidebar } from "@/components/app-sidebar"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import Script from "next/script"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ColorThemeProvider>
            <CardSettingsProvider>
              <PersonaProvider>
                <SidebarProvider>
                  <AppSidebar />
                  <SidebarInset>

                  <div className="flex flex-1 flex-col h-full max-h-screen w-full max-w-full overflow-hidden">
                    {children}
                  </div>
                </SidebarInset>
              </SidebarProvider>
            </PersonaProvider>
          </CardSettingsProvider>
        </ColorThemeProvider>
        </ThemeProvider>
        <Toaster />
        {process.env.NODE_ENV === "development" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
          />
        )}
      </body>
    </html>
  );
}
