import type { Metadata } from "next";
import { DynamicBreadcrumb } from "@/components/bank-dashboard/dynamic-breadcrumb"
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ColorThemeProvider } from "@/components/color-theme-provider"
import { AppSidebar } from "@/components/app-sidebar"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"

// ... imports

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ColorThemeProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>

                <div className="flex flex-1 flex-col h-full max-h-screen w-full max-w-full overflow-hidden">
                  {children}
                </div>
              </SidebarInset>
            </SidebarProvider>
          </ColorThemeProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
